# CMake generated Testfile for 
# Source directory: D:/dev/guideXOS_Developer_Studio
# Build directory: D:/dev/guideXOS_Developer_Studio/build-phase28p-host
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(developer_studio_model_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_model_test.exe")
set_tests_properties(developer_studio_model_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;59;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_project_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_project_test.exe")
set_tests_properties(developer_studio_project_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;60;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_build_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_build_test.exe")
set_tests_properties(developer_studio_build_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;67;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_source_enumeration_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_source_enumeration_test.exe")
set_tests_properties(developer_studio_source_enumeration_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;74;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_run_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_run_test.exe")
set_tests_properties(developer_studio_run_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;81;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_output_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_output_test.exe")
set_tests_properties(developer_studio_output_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;88;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_navigation_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_navigation_test.exe")
set_tests_properties(developer_studio_navigation_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;95;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_syntax_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_syntax_test.exe")
set_tests_properties(developer_studio_syntax_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;102;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_find_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_find_test.exe")
set_tests_properties(developer_studio_find_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;109;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_project_search_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_project_search_test.exe")
set_tests_properties(developer_studio_project_search_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;116;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_symbol_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_symbol_test.exe")
set_tests_properties(developer_studio_symbol_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;123;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_navigation_definition_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_navigation_definition_test.exe")
set_tests_properties(developer_studio_navigation_definition_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;130;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_reference_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_reference_test.exe")
set_tests_properties(developer_studio_reference_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;137;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_rename_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_rename_test.exe")
set_tests_properties(developer_studio_rename_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;144;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_completion_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_completion_test.exe")
set_tests_properties(developer_studio_completion_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;151;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_signature_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_signature_test.exe")
set_tests_properties(developer_studio_signature_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;158;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_include_graph_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_include_graph_test.exe")
set_tests_properties(developer_studio_include_graph_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;165;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_relationship_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_relationship_test.exe")
set_tests_properties(developer_studio_relationship_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;172;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_ownership_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_ownership_test.exe")
set_tests_properties(developer_studio_ownership_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;179;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_types_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_types_test.exe")
set_tests_properties(developer_studio_types_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;186;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debug_symbols_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_debug_symbols_test.exe")
set_tests_properties(developer_studio_debug_symbols_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;199;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_debugger_test.exe")
set_tests_properties(developer_studio_debugger_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;200;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_step_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_debugger_step_test.exe")
set_tests_properties(developer_studio_debugger_step_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;207;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_stack_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_debugger_stack_test.exe")
set_tests_properties(developer_studio_debugger_stack_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;214;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_structured_variables_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_debugger_structured_variables_test.exe")
set_tests_properties(developer_studio_debugger_structured_variables_test PROPERTIES  WORKING_DIRECTORY "D:/dev/guideXOS_Developer_Studio" _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;227;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_variables_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_debugger_variables_test.exe")
set_tests_properties(developer_studio_debugger_variables_test PROPERTIES  WORKING_DIRECTORY "D:/dev/guideXOS_Developer_Studio" _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;228;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_watches_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_debugger_watches_test.exe")
set_tests_properties(developer_studio_debugger_watches_test PROPERTIES  WORKING_DIRECTORY "D:/dev/guideXOS_Developer_Studio" _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;235;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_conditional_breakpoints_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_debugger_conditional_breakpoints_test.exe")
set_tests_properties(developer_studio_debugger_conditional_breakpoints_test PROPERTIES  WORKING_DIRECTORY "D:/dev/guideXOS_Developer_Studio" _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;242;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debug_editor_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_debug_editor_test.exe")
set_tests_properties(developer_studio_debug_editor_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;249;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_workspace_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_debugger_workspace_test.exe")
set_tests_properties(developer_studio_debugger_workspace_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;256;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debug_tips_test "D:/dev/guideXOS_Developer_Studio/build-phase28p-host/developer_studio_debug_tips_test.exe")
set_tests_properties(developer_studio_debug_tips_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;263;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
