# CMake generated Testfile for 
# Source directory: D:/dev/guideXOS_Developer_Studio
# Build directory: D:/dev/guideXOS_Developer_Studio/build-native
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(developer_studio_model_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_model_test.exe")
set_tests_properties(developer_studio_model_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;58;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_project_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_project_test.exe")
set_tests_properties(developer_studio_project_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;59;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_build_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_build_test.exe")
set_tests_properties(developer_studio_build_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;66;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_source_enumeration_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_source_enumeration_test.exe")
set_tests_properties(developer_studio_source_enumeration_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;73;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_run_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_run_test.exe")
set_tests_properties(developer_studio_run_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;80;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_output_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_output_test.exe")
set_tests_properties(developer_studio_output_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;87;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_navigation_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_navigation_test.exe")
set_tests_properties(developer_studio_navigation_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;94;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_syntax_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_syntax_test.exe")
set_tests_properties(developer_studio_syntax_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;101;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_find_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_find_test.exe")
set_tests_properties(developer_studio_find_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;108;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_project_search_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_project_search_test.exe")
set_tests_properties(developer_studio_project_search_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;115;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_symbol_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_symbol_test.exe")
set_tests_properties(developer_studio_symbol_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;122;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_navigation_definition_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_navigation_definition_test.exe")
set_tests_properties(developer_studio_navigation_definition_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;129;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_reference_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_reference_test.exe")
set_tests_properties(developer_studio_reference_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;136;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_rename_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_rename_test.exe")
set_tests_properties(developer_studio_rename_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;143;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_completion_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_completion_test.exe")
set_tests_properties(developer_studio_completion_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;150;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_signature_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_signature_test.exe")
set_tests_properties(developer_studio_signature_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;157;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_include_graph_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_include_graph_test.exe")
set_tests_properties(developer_studio_include_graph_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;164;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_relationship_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_relationship_test.exe")
set_tests_properties(developer_studio_relationship_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;171;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_ownership_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_ownership_test.exe")
set_tests_properties(developer_studio_ownership_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;178;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_types_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_types_test.exe")
set_tests_properties(developer_studio_types_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;185;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debug_symbols_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_debug_symbols_test.exe")
set_tests_properties(developer_studio_debug_symbols_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;198;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_debugger_test.exe")
set_tests_properties(developer_studio_debugger_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;199;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_step_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_debugger_step_test.exe")
set_tests_properties(developer_studio_debugger_step_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;206;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_stack_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_debugger_stack_test.exe")
set_tests_properties(developer_studio_debugger_stack_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;213;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_structured_variables_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_debugger_structured_variables_test.exe")
set_tests_properties(developer_studio_debugger_structured_variables_test PROPERTIES  WORKING_DIRECTORY "D:/dev/guideXOS_Developer_Studio" _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;226;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_variables_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_debugger_variables_test.exe")
set_tests_properties(developer_studio_debugger_variables_test PROPERTIES  WORKING_DIRECTORY "D:/dev/guideXOS_Developer_Studio" _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;227;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_watches_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_debugger_watches_test.exe")
set_tests_properties(developer_studio_debugger_watches_test PROPERTIES  WORKING_DIRECTORY "D:/dev/guideXOS_Developer_Studio" _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;234;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_conditional_breakpoints_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_debugger_conditional_breakpoints_test.exe")
set_tests_properties(developer_studio_debugger_conditional_breakpoints_test PROPERTIES  WORKING_DIRECTORY "D:/dev/guideXOS_Developer_Studio" _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;241;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debug_editor_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_debug_editor_test.exe")
set_tests_properties(developer_studio_debug_editor_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;248;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_workspace_test "D:/dev/guideXOS_Developer_Studio/build-native/developer_studio_debugger_workspace_test.exe")
set_tests_properties(developer_studio_debugger_workspace_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;255;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
