# CMake generated Testfile for 
# Source directory: D:/dev/guideXOS_Developer_Studio
# Build directory: D:/dev/guideXOS_Developer_Studio/build-phase5-native
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(developer_studio_model_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_model_test.exe")
set_tests_properties(developer_studio_model_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;55;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_project_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_project_test.exe")
set_tests_properties(developer_studio_project_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;56;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_build_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_build_test.exe")
set_tests_properties(developer_studio_build_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;63;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_run_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_run_test.exe")
set_tests_properties(developer_studio_run_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;70;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_output_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_output_test.exe")
set_tests_properties(developer_studio_output_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;77;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_navigation_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_navigation_test.exe")
set_tests_properties(developer_studio_navigation_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;84;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_syntax_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_syntax_test.exe")
set_tests_properties(developer_studio_syntax_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;91;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_find_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_find_test.exe")
set_tests_properties(developer_studio_find_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;98;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_project_search_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_project_search_test.exe")
set_tests_properties(developer_studio_project_search_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;105;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_symbol_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_symbol_test.exe")
set_tests_properties(developer_studio_symbol_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;112;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_navigation_definition_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_navigation_definition_test.exe")
set_tests_properties(developer_studio_navigation_definition_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;119;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_reference_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_reference_test.exe")
set_tests_properties(developer_studio_reference_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;126;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_rename_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_rename_test.exe")
set_tests_properties(developer_studio_rename_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;133;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_completion_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_completion_test.exe")
set_tests_properties(developer_studio_completion_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;140;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_signature_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_signature_test.exe")
set_tests_properties(developer_studio_signature_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;147;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_include_graph_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_include_graph_test.exe")
set_tests_properties(developer_studio_include_graph_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;154;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_relationship_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_relationship_test.exe")
set_tests_properties(developer_studio_relationship_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;161;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_ownership_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_ownership_test.exe")
set_tests_properties(developer_studio_ownership_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;168;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_types_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_types_test.exe")
set_tests_properties(developer_studio_types_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;175;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debug_symbols_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_debug_symbols_test.exe")
set_tests_properties(developer_studio_debug_symbols_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;188;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_debugger_test.exe")
set_tests_properties(developer_studio_debugger_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;189;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_step_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_debugger_step_test.exe")
set_tests_properties(developer_studio_debugger_step_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;196;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_stack_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_debugger_stack_test.exe")
set_tests_properties(developer_studio_debugger_stack_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;203;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_structured_variables_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_debugger_structured_variables_test.exe")
set_tests_properties(developer_studio_debugger_structured_variables_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;216;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_variables_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_debugger_variables_test.exe")
set_tests_properties(developer_studio_debugger_variables_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;217;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
