# CMake generated Testfile for 
# Source directory: D:/dev/guideXOS_Developer_Studio
# Build directory: D:/dev/guideXOS_Developer_Studio/build-phase5-native
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(developer_studio_model_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_model_test.exe")
set_tests_properties(developer_studio_model_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;53;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_project_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_project_test.exe")
set_tests_properties(developer_studio_project_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;54;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_build_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_build_test.exe")
set_tests_properties(developer_studio_build_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;61;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_run_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_run_test.exe")
set_tests_properties(developer_studio_run_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;68;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_output_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_output_test.exe")
set_tests_properties(developer_studio_output_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;75;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_navigation_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_navigation_test.exe")
set_tests_properties(developer_studio_navigation_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;82;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_syntax_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_syntax_test.exe")
set_tests_properties(developer_studio_syntax_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;89;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_find_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_find_test.exe")
set_tests_properties(developer_studio_find_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;96;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_project_search_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_project_search_test.exe")
set_tests_properties(developer_studio_project_search_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;103;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_symbol_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_symbol_test.exe")
set_tests_properties(developer_studio_symbol_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;110;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_navigation_definition_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_navigation_definition_test.exe")
set_tests_properties(developer_studio_navigation_definition_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;117;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_reference_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_reference_test.exe")
set_tests_properties(developer_studio_reference_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;124;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_rename_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_rename_test.exe")
set_tests_properties(developer_studio_rename_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;131;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_completion_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_completion_test.exe")
set_tests_properties(developer_studio_completion_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;138;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_signature_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_signature_test.exe")
set_tests_properties(developer_studio_signature_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;145;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_include_graph_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_include_graph_test.exe")
set_tests_properties(developer_studio_include_graph_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;152;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_relationship_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_relationship_test.exe")
set_tests_properties(developer_studio_relationship_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;159;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_ownership_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_ownership_test.exe")
set_tests_properties(developer_studio_ownership_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;166;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_types_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_types_test.exe")
set_tests_properties(developer_studio_types_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;173;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debug_symbols_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_debug_symbols_test.exe")
set_tests_properties(developer_studio_debug_symbols_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;186;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_debugger_test.exe")
set_tests_properties(developer_studio_debugger_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;187;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
add_test(developer_studio_debugger_step_test "D:/dev/guideXOS_Developer_Studio/build-phase5-native/developer_studio_debugger_step_test.exe")
set_tests_properties(developer_studio_debugger_step_test PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;194;add_test;D:/dev/guideXOS_Developer_Studio/CMakeLists.txt;0;")
